### ISSUE TITLE
Pushed menus for top and bottom?

### ISSUE THREAD

**Issue by IngwiePhoenix** [codrops/Blueprint-SlidePushMenus#1]
Hey there!

I am working on a project in which I need to actually be able to display a push-in menu in all four sides - top, right, bottom and left. I am about to add JavaScript to it to automatically display it once the cursor is nearby a specific, transparent, DIV element whose only purpose is to detect and trigger a push event.

Can you maybe help me get the pushbottom and pushtop classes working? I tried to figure it out, but I kinda ended up just blutly looking at the code.

I have used the download provided from the page linked in the readme file.

Regards, Ingwie!

**Comment by botelho** [comment]
Hi, could you please make this request in the comments area of the original article? Maybe somebody else will give you some tips on this? Thanks
